### ISSUE TITLE
Add Near WebWallet or Sender support

### ISSUE THREAD

**Issue by GaloisField2718** [uinb/fusotao#36]
**Motivation**

There isn't way to connect my regulars Near wallet on Fusotao.  

**Suggested Solution**

Use regular Near.js framework for integration. 

**Alternatives**

It's possible to link with Sender also but it's not related with Near.js I think.

**Additional Information**

**https://docs.near.org/tools/near-api-js/quick-reference** 

```js
// const walletConnection = new WalletConnection(nearConnection);
walletConnection.requestSignIn(
  "example-contract.testnet", // contract requesting access
  "Example App", // optional title
  "http://YOUR-URL.com/success", // optional redirect URL on success
  "http://YOUR-URL.com/failure" // optional redirect URL on failure
);
```

Let see if works or not. 
I'm available to chat deeper with you but I think it's quiet easy.

Have a nice day,

GF

**Comment by kb1ns** [comment]
Well, we'd love to but it's not simple because dex upon fusotao can only recognize valid fusotao addresses and tokens in those addresses need to be authorized then the dex can prove the trading behaviours.
Currently, users need to transfer their tokens from near to fusotao chain through the oct bridge which can be considered as a safe way because it is a trustless bridge doesn't rely on the human trust.
A realistic way of supporting near wallet is to implement ICA(interchain account spec) feature over the bridge. For instance, a near user can sign a transaction doesn't contain any fund transfer but a raw data which can be decoded into a transaction of fusotao chain, after bridged the transaction to fusotao chain, a fusotao address will be implied without private key, e.g. hash(abcde.near) => 5Gv..., this address can represent the near account and execute the decoded raw data(e.g. authorize, transfer)

A good news is that our team is developing the fantastic feature but unluckily not for near, eth instead. It will be published very soon, please check the testnet.

**Comment by GaloisField2718** [comment]
Okay I see. Thank you for your answer. 
I'm a bit disappointed that on Octopus Network it isn't so easy to use appChain for Near users. It's built on Near but AppChain are so far from Near chain... 
I heard Sheldon told about a translator between AppChain's contracts and Near mainnet but apparently it's really in development and not for now, neither for this year or next...
Moreover, why have you choosing Octopus for developing your DEX if the goal is to link it with Ethereum. 
There are better Layer 2 to make it no ?!

Otherwise, thank you again for your comment.

**Comment by kb1ns** [comment]
> Okay I see. Thank you for your answer. I'm a bit disappointed that on Octopus Network it isn't so easy to use appChain for Near users. It's built on Near but AppChain are so far from Near chain... I heard Sheldon told about a translator between AppChain's contracts and Near mainnet but apparently it's really in development and not for now, neither for this year or next... Moreover, why have you choosing Octopus for developing your DEX if the goal is to link it with Ethereum. There are better Layer 2 to make it no ?!
> 
> Otherwise, thank you again for your comment.

Implementing on near is a little bit dangerous because near is account based and the accounts can be raped which may cause some ub if a near account has bound an appchain address, while it is safe on ETH because ETH is pubkey based.

We do believe the appchain way is the future of blockchain world rather than smart contract, what's why we insist to develop our whole project on Octopus.
